apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-readonly-user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-developer-user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-agent
