apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This file is used to deploy Traefik as an Ingress Controller in a Kubernetes cluster.
resources:
  - https://raw.githubusercontent.com/traefik/traefik/v3.5/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - service.yaml
  - deployment.yaml
  - ingressclass.yaml
