apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
stringData:
  # Your master key for the proxy server. Can use this to send /chat/completion requests etc
  LITELLM_MASTER_KEY: "sk-fantastic-people-alive" 
  # Can NOT CHANGE THIS ONCE SET - It is used to encrypt/decrypt credentials stored in DB. If value of 'LITELLM_SALT_KEY' changes your models cannot be retrieved from DB
  LITELLM_SALT_KEY: "sk-super-secret-salt-key" 
  