apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-agent
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: agent
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - nodes/stats
      - nodes/proxy
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
