apiVersion: v1
kind: Secret
metadata:
  name: otel-collector-secret
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: agent
type: Opaque
stringData:
  GRAFANA_CLOUD_OTLP_ENDPOINT: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
  GRAFANA_CLOUD_API_KEY: "CHANGEME"
  CLUSTER_NAME: "default"
