apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-tools

resources:
  - namespace.yaml
  - ../../components/apps/ai-models/ollama

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/overlay: quickstart

patches:
  - path: patches/ollama-pvc-size.yaml
    target:
      kind: PersistentVolumeClaim
      name: pvc-ollama
  - path: patches/ollama-resources.yaml
    target:
      kind: StatefulSet
      name: ollama
