apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shared-cert
  namespace: shared
spec:
  dnsNames:
    - "*.shared.cdc-event-sourcing.local"
    - "registry.cdc-event-sourcing.local"
