apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - name: mosquitto-vol
              mountPath: /mosquitto/data
              subPath: apps/mosquitto/data
            - name: mosquitto-vol
              mountPath: /mosquitto/config
              subPath: apps/mosquitto/config
            - name: mosquitto-vol
              mountPath: /mosquitto/log
              subPath: apps/mosquitto/log
      volumes:
        - name: mosquitto-vol
          persistentVolumeClaim:
            claimName: pvc-mosquitto
      restartPolicy: Always
