#!/usr/bin/env python3
"""Compile the Forjate wiki from the Kustomize tree.

The Kustomize tree under k8s/ is the source of truth. This script derives one
page per component, overlay and base app, filling the "Declared" zone with facts
read straight out of the YAML and computing consumed_by backlinks from real
resource references.

The "Notes" zone of every page is preserved verbatim across runs, so prose
written by a human or an agent survives recompilation.

See wiki/SCHEMA.md for the conventions this script implements.

Usage:
    poetry run python scripts/wiki-compile.py [--check]

    --check   report what would change without writing (for CI)
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required. Run: poetry install")

REPO = Path(__file__).resolve().parent.parent
K8S = REPO / "k8s"
WIKI = REPO / "wiki"

DECLARED_BEGIN = "<!-- BEGIN DECLARED (generated by scripts/wiki-compile.py — do not edit) -->"
DECLARED_END = "<!-- END DECLARED -->"
NOTES_HEADING = "## Notes"

NOTES_PLACEHOLDER = (
    "_No notes yet. This zone is for interpretation: what this is for, how it\n"
    "composes with others, gotchas. It survives recompilation — write freely._"
)

IMAGE_RE = re.compile(r"^\s*(?:-\s+)?image:\s*[\"']?([^\"'\s]+)", re.MULTILINE)
REMOTE_RE = re.compile(r"^(https?://|ssh://|git@|github\.com/)")


@dataclass
class Page:
    """One compiler-owned wiki page derived from a directory in k8s/."""

    name: str
    kind: str                      # component | overlay | base
    category: str | None
    source: Path                   # absolute path to the source directory
    rel_source: str                # repo-relative, goes into frontmatter
    out: Path                      # absolute path of the wiki page

    header: str = ""               # leading comment block of kustomization.yaml
    resources: list[str] = field(default_factory=list)
    local_refs: list[str] = field(default_factory=list)   # resolved sibling dirs
    remote_refs: list[str] = field(default_factory=list)
    images: list[str] = field(default_factory=list)
    kinds: list[str] = field(default_factory=list)        # k8s kinds declared
    labels: dict = field(default_factory=dict)
    patches: list[str] = field(default_factory=list)
    configmaps: list[str] = field(default_factory=list)
    secrets: list[str] = field(default_factory=list)
    namespace: str | None = None
    parent: str | None = None      # set when nested inside another kustomization
    summary: str = ""             # one-liner used by index.md
    consumed_by: list[str] = field(default_factory=list)  # computed backlinks
    depends_links: list[str] = field(default_factory=list)  # local_refs resolved to pages
    warnings: list[str] = field(default_factory=list)


def rel(p: Path) -> str:
    return str(p.relative_to(REPO))


def load_kustomization(path: Path) -> tuple[dict, str, list[str]]:
    """Return (parsed doc, leading comment block, warnings)."""
    warnings: list[str] = []
    text = path.read_text(encoding="utf-8")

    header_lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            header_lines.append(stripped.lstrip("#").strip())
        elif not stripped:
            if header_lines:
                header_lines.append("")
        elif header_lines or stripped.startswith(("apiVersion:", "kind:", "resources:")):
            break
    header = "\n".join(header_lines).strip()

    try:
        doc = yaml.safe_load(text) or {}
    except yaml.YAMLError as exc:
        warnings.append(f"kustomization.yaml did not parse: {exc}")
        doc = {}
    if not isinstance(doc, dict):
        warnings.append("kustomization.yaml is not a mapping")
        doc = {}
    return doc, header, warnings


def scan_manifests(directory: Path) -> tuple[list[str], list[str]]:
    """Collect container images and Kubernetes kinds declared in a directory."""
    images: set[str] = set()
    kinds: set[str] = set()
    for f in sorted(directory.rglob("*.yaml")):
        if f.name == "kustomization.yaml":
            continue
        try:
            text = f.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        images.update(IMAGE_RE.findall(text))
        try:
            for doc in yaml.safe_load_all(text):
                if isinstance(doc, dict) and isinstance(doc.get("kind"), str):
                    kinds.add(doc["kind"])
        except yaml.YAMLError:
            # Overlay patch fragments are often not standalone documents.
            pass
    return sorted(images), sorted(kinds)


def extract(page: Page) -> None:
    kfile = page.source / "kustomization.yaml"
    if not kfile.exists():
        page.warnings.append("no kustomization.yaml in this directory")
        return

    doc, header, warnings = load_kustomization(kfile)
    page.header = header
    page.warnings.extend(warnings)

    page.namespace = doc.get("namespace")

    for r in doc.get("resources", []) or []:
        if not isinstance(r, str):
            continue
        page.resources.append(r)
        if REMOTE_RE.match(r):
            page.remote_refs.append(r)
        else:
            target = (page.source / r).resolve()
            if target.is_dir() and K8S in target.parents:
                page.local_refs.append(rel(target))

    for lbl in doc.get("labels", []) or []:
        if isinstance(lbl, dict):
            page.labels.update(lbl.get("pairs", {}) or {})
    if isinstance(doc.get("commonLabels"), dict):
        page.labels.update(doc["commonLabels"])

    for p in doc.get("patches", []) or []:
        if isinstance(p, dict):
            target = p.get("target", {}) or {}
            desc = target.get("kind", "?")
            if target.get("name"):
                desc += f"/{target['name']}"
            if target.get("namespace"):
                desc += f" (ns: {target['namespace']})"
            page.patches.append(f"{p.get('path', 'inline')} → {desc}")

    for gen, bucket in (("configMapGenerator", page.configmaps),
                        ("secretGenerator", page.secrets)):
        for entry in doc.get(gen, []) or []:
            if isinstance(entry, dict) and entry.get("name"):
                ns = entry.get("namespace")
                bucket.append(f"{entry['name']}" + (f" (ns: {ns})" if ns else ""))

    page.images, page.kinds = scan_manifests(page.source)


# Directories that are structural parts of a kustomization, never pages of their own.
STRUCTURAL = {"namespaces", "patches", "configs", "secrets", "templates"}


def is_page_dir(d: Path, root: Path) -> bool:
    """A directory earns a page if it declares a kustomization and is not a
    structural sub-directory of one (patches/, secrets/, namespaces/, ...)."""
    if not (d / "kustomization.yaml").exists():
        return False
    return not any(part in STRUCTURAL for part in d.relative_to(root).parts)


def discover() -> list[Page]:
    pages: list[Page] = []
    seen: dict[Path, Page] = {}

    # Components: everything under k8s/components, not just apps/.
    comps = K8S / "components"
    if comps.is_dir():
        for kfile in sorted(comps.rglob("kustomization.yaml")):
            d = kfile.parent
            if not is_page_dir(d, comps):
                continue
            parts = d.relative_to(comps).parts
            # apps/databases/postgres -> category "databases", name "databases-postgres"
            # bundles/temporal-stack  -> category "bundles",   name "bundles-temporal-stack"
            if parts[0] == "apps":
                rest = parts[1:]
                category = rest[0] if len(rest) > 1 else "standalone"
            else:
                rest = parts
                category = parts[0]
            if not rest:
                continue
            page = Page(
                name="-".join(rest), kind="component", category=category,
                source=d, rel_source=rel(d),
                out=WIKI / "components" / f"{'-'.join(rest)}.md",
            )
            pages.append(page)
            seen[d] = page

    # Overlays, including nested ones (multi-tenant-pattern/tenants/client-a).
    overlays = K8S / "overlays"
    if overlays.is_dir():
        for kfile in sorted(overlays.rglob("kustomization.yaml")):
            d = kfile.parent
            if not is_page_dir(d, overlays):
                continue
            parts = d.relative_to(overlays).parts
            page = Page(
                name="-".join(parts), kind="overlay",
                category=parts[0] if len(parts) > 1 else None,
                source=d, rel_source=rel(d),
                out=WIKI / "overlays" / f"{'-'.join(parts)}.md",
            )
            pages.append(page)
            seen[d] = page

    base = K8S / "base"
    if (base / "kustomization.yaml").exists():
        page = Page(name="base", kind="base", category=None,
                    source=base, rel_source=rel(base),
                    out=WIKI / "base" / "base.md")
        pages.append(page)
        seen[base] = page
    for d in sorted(p for p in (base / "apps").glob("*") if p.is_dir()):
        if (d / "kustomization.yaml").exists():
            page = Page(name=d.name, kind="base", category="base-app",
                        source=d, rel_source=rel(d),
                        out=WIKI / "base" / f"{d.name}.md")
            pages.append(page)
            seen[d] = page

    # Nesting: a page whose enclosing directory is also a page is a sub-page.
    for page in pages:
        for ancestor in page.source.parents:
            if ancestor in seen:
                page.parent = link_for(seen[ancestor])
                break
            if ancestor == K8S:
                break

    return pages


def link_for(page: Page) -> str:
    return f"{page.out.parent.name}/{page.out.stem}"


def compute_backlinks(pages: list[Page]) -> None:
    """consumed_by is derived from real resources: references, never hand-written."""
    by_source = {p.rel_source: p for p in pages}
    for page in pages:
        for ref in page.local_refs:
            target = by_source.get(ref)
            if target and target is not page:
                target.consumed_by.append(link_for(page))
                page.depends_links.append(link_for(target))
    for page in pages:
        page.consumed_by = sorted(set(page.consumed_by))


def source_last_commit(rel_path: str) -> str | None:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", rel_path],
            cwd=REPO, capture_output=True, text=True, timeout=15,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    value = out.stdout.strip()
    return value or None


def bullets(items: list[str], empty: str = "_none declared_") -> str:
    if not items:
        return empty
    return "\n".join(f"- `{i}`" for i in items)


def render_declared(page: Page) -> str:
    lines: list[str] = []

    if page.header:
        lines += ["> Source comment, verbatim from `kustomization.yaml`:", ">",
                  "\n".join(f"> {l}" if l else ">" for l in page.header.splitlines()),
                  ""]

    lines += [f"**Source:** [`{page.rel_source}/`](../../{page.rel_source}/)", ""]

    if page.parent:
        lines += [f"**Part of:** [{page.parent}](../{page.parent}.md)", ""]

    if page.namespace:
        lines += [f"**Namespace:** `{page.namespace}`", ""]

    lines += ["### Declared resources", "", bullets(page.resources), ""]

    if page.kinds:
        lines += ["### Kubernetes kinds", "",
                  ", ".join(f"`{k}`" for k in page.kinds), ""]

    if page.images:
        lines += ["### Container images", "", bullets(page.images), ""]

    if page.remote_refs:
        lines += ["### Remote references", "", bullets(page.remote_refs), ""]

    if page.local_refs:
        resolved = dict(zip(page.local_refs, page.depends_links))
        entries = []
        for r in page.local_refs:
            link = resolved.get(r)
            # Linked when the dependency has a page of its own; bare path when
            # it is a directory the compiler does not turn into a page.
            entries.append(f"- [{link}](../{link}.md)" if link else f"- `{r}`")
        lines += ["### Depends on", "", "\n".join(entries), ""]

    if page.patches:
        lines += ["### Patches", "", bullets(page.patches), ""]

    if page.configmaps:
        lines += ["### Generated ConfigMaps", "", bullets(page.configmaps), ""]

    if page.secrets:
        lines += ["### Generated Secrets", "", bullets(page.secrets),
                  "",
                  "_Names only. Values come from overlay `.env` files or SealedSecrets "
                  "and are never recorded here._", ""]

    if page.labels:
        lines += ["### Labels", "",
                  "\n".join(f"- `{k}: {v}`" for k, v in sorted(page.labels.items())), ""]

    if page.consumed_by:
        lines += ["### Consumed by", "",
                  "\n".join(f"- [{c}](../{c}.md)" for c in page.consumed_by), ""]
    elif page.kind == "component":
        lines += ["### Consumed by", "",
                  "_No overlay in this repo references this component._", ""]

    if page.warnings:
        lines += ["### Compiler warnings", "",
                  "\n".join(f"- {w}" for w in page.warnings), ""]

    return "\n".join(lines).rstrip() + "\n"


def existing_summary(path: Path) -> str | None:
    """A one-line summary an agent wrote into frontmatter. Preserved across
    recompiles and used as the page's line in index.md."""
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    try:
        fm = yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return None
    if not isinstance(fm, dict):
        return None
    # Only a summary explicitly marked as authored survives; a derived one is
    # regenerated, otherwise a bad early guess would be frozen forever.
    if fm.get("summary_source") != "authored":
        return None
    value = fm.get("summary")
    return str(value).strip() if value else None


def derive_summary(page: Page) -> str:
    """Fallback one-liner when nobody has written a summary yet."""
    for line in page.header.splitlines():
        line = line.strip()
        # Many kustomizations open with their own path as a comment; that is a
        # filename, not a summary. Skip down to the first line that says something.
        if not line or "kustomization.yaml" in line or line.startswith("k8s/"):
            continue
        return line.rstrip(".")
    if page.images:
        return f"deploys `{page.images[0]}`"
    if page.remote_refs:
        return f"vendors `{page.remote_refs[0].rsplit('/', 1)[-1]}`"
    if page.kinds:
        return "declares " + ", ".join(f"`{k}`" for k in page.kinds[:3])
    if page.local_refs:
        names = [r.rsplit("/", 1)[-1] for r in page.local_refs[:3]]
        return "composes " + ", ".join(f"`{n}`" for n in names)
    if page.resources:
        return f"aggregates {len(page.resources)} resource(s)"
    return "_no summary yet_"


def existing_notes(path: Path) -> str | None:
    """Pull the Notes zone out of an existing page so prose survives a recompile."""
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    idx = text.find(NOTES_HEADING)
    if idx == -1:
        return None
    body = text[idx + len(NOTES_HEADING):].strip("\n")
    return body if body.strip() and body.strip() != NOTES_PLACEHOLDER else None


def render_page(page: Page, compiled_at: str) -> str:
    fm = {
        "title": page.name,
        "kind": page.kind,
        "sources": [page.rel_source],
        "compiled_at": compiled_at,
    }
    if page.category:
        fm["category"] = page.category
    if page.parent:
        fm["parent"] = page.parent
    if page.consumed_by:
        fm["consumed_by"] = page.consumed_by
    last = source_last_commit(page.rel_source)
    if last:
        fm["source_last_commit"] = last
    authored = existing_summary(page.out)
    page.summary = authored or derive_summary(page)
    fm["summary"] = page.summary
    fm["summary_source"] = "authored" if authored else "derived"

    front = yaml.safe_dump(fm, sort_keys=False, default_flow_style=False).strip()
    notes = existing_notes(page.out) or NOTES_PLACEHOLDER

    return (
        f"---\n{front}\n---\n\n"
        f"# {page.name}\n\n"
        f"{DECLARED_BEGIN}\n\n"
        f"{render_declared(page)}\n"
        f"{DECLARED_END}\n\n"
        f"{NOTES_HEADING}\n\n{notes}\n"
    )


def read_concepts() -> list[tuple[str, str, str]]:
    """Concept pages are agent-authored and have no counterpart in k8s/.
    They still belong in the index, so read their title and summary."""
    out = []
    concepts = WIKI / "concepts"
    if not concepts.is_dir():
        return out
    for f in sorted(concepts.glob("*.md")):
        title, summary = f.stem, ""
        text = f.read_text(encoding="utf-8")
        if text.startswith("---"):
            end = text.find("\n---", 3)
            if end != -1:
                try:
                    fm = yaml.safe_load(text[3:end]) or {}
                    if isinstance(fm, dict):
                        title = str(fm.get("title") or title)
                        summary = str(fm.get("summary") or "")
                except yaml.YAMLError:
                    pass
        out.append((title, f"concepts/{f.stem}.md", summary))
    return out


def render_index(pages: list[Page], compiled_at: str) -> str:
    lines = [
        "---",
        "title: index",
        "kind: index",
        f"compiled_at: '{compiled_at}'",
        "---",
        "",
        "# Forjate wiki — index",
        "",
        "Content-oriented catalog of the whole wiki. **Agents: read this page "
        "first**, find the relevant entries, then open those pages.",
        "",
        "Everything under `base/`, `components/` and `overlays/` is compiled from "
        "`k8s/**` by `scripts/wiki-compile.py`. Pages under `concepts/` are written "
        "by agents and hold synthesis that no single directory contains.",
        "",
        f"Conventions and maintenance rules: [SCHEMA.md](SCHEMA.md) · "
        f"History: [log.md](log.md) · Built on "
        f"[Karpathy's LLM Wiki pattern]"
        f"(https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f)",
        "",
    ]

    concepts = read_concepts()
    lines += ["## Concepts", ""]
    if concepts:
        for title, link, summary in concepts:
            lines.append(f"- [{title}]({link})" + (f" — {summary}" if summary else ""))
    else:
        lines.append("_No concept pages yet._")
    lines.append("")

    base_pages = [p for p in pages if p.kind == "base"]
    if base_pages:
        lines += ["## Base", "",
                  "The foundation every tenant inherits.", ""]
        for pg in sorted(base_pages, key=lambda x: (x.category or "", x.name)):
            lines.append(f"- [{pg.name}](base/{pg.out.stem}.md) — {pg.summary}")
        lines.append("")

    comps = [p for p in pages if p.kind == "component"]
    if comps:
        lines += ["## Components", "",
                  f"{len(comps)} pages. Optional building blocks an overlay can "
                  "activate.", ""]
        by_cat: dict[str, list[Page]] = {}
        for pg in comps:
            by_cat.setdefault(pg.category or "uncategorized", []).append(pg)
        for cat in sorted(by_cat):
            lines += [f"### {cat}", ""]
            for pg in sorted(by_cat[cat], key=lambda x: x.name):
                used = len(pg.consumed_by)
                tail = f" · used by {used}" if used else " · unused in this repo"
                indent = "  " if pg.parent else ""
                lines.append(
                    f"{indent}- [{pg.name}](components/{pg.out.stem}.md) — "
                    f"{pg.summary}{tail}"
                )
            lines.append("")

    ovl = [p for p in pages if p.kind == "overlay"]
    if ovl:
        lines += ["## Overlays", "",
                  "Concrete environments assembled from base + components.", ""]
        for pg in sorted(ovl, key=lambda x: x.name):
            n = len(pg.local_refs)
            lines.append(
                f"- [{pg.name}](overlays/{pg.out.stem}.md) — {pg.summary}"
                f" · {n} local reference{'s' if n != 1 else ''}"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def append_log(entry: str) -> None:
    """Append-only, with the fixed grep-parseable prefix the schema mandates."""
    log = WIKI / "log.md"
    if not log.exists():
        log.write_text(
            "# Wiki log\n\n"
            "Append-only history of this wiki. Every entry starts with\n"
            "`## [YYYY-MM-DD] <type> | <detail>` so it stays parseable:\n\n"
            "```sh\n"
            'grep "^## \\[" wiki/log.md | tail -5\n'
            "```\n\n"
            "Types: `compile`, `concept`, `lint`, `query`.\n\n",
            encoding="utf-8",
        )
    with log.open("a", encoding="utf-8") as fh:
        fh.write(entry + "\n")


def main() -> int:
    ap = argparse.ArgumentParser(description="Compile the Forjate wiki from k8s/")
    ap.add_argument("--check", action="store_true",
                    help="report changes without writing (CI mode)")
    args = ap.parse_args()

    pages = discover()
    for page in pages:
        extract(page)
    compute_backlinks(pages)

    compiled_at = date.today().isoformat()
    written, changed, unchanged = 0, [], 0

    # Ignore compiled_at churn when deciding whether anything really changed.
    def strip(t):
        return re.sub(r"^compiled_at: .*$", "", t or "", flags=re.MULTILINE)

    for page in pages:
        content = render_page(page, compiled_at)
        prior = page.out.read_text(encoding="utf-8") if page.out.exists() else None
        if prior is not None and strip(prior) == strip(content):
            unchanged += 1
            continue
        changed.append(rel(page.out))
        if not args.check:
            page.out.parent.mkdir(parents=True, exist_ok=True)
            page.out.write_text(content, encoding="utf-8")
            written += 1

    counts = {}
    for p in pages:
        counts[p.kind] = counts.get(p.kind, 0) + 1
    summary = ", ".join(f"{v} {k}" for k, v in sorted(counts.items()))

    # index.md must be evaluated before the --check early return, otherwise CI
    # would pass with a stale catalog.
    index_path = WIKI / "index.md"
    index_content = render_index(pages, compiled_at)
    prior_index = index_path.read_text(encoding="utf-8") if index_path.exists() else None
    if strip(prior_index) != strip(index_content):
        changed.append(rel(index_path))
        if not args.check:
            index_path.write_text(index_content, encoding="utf-8")
            written += 1

    if changed and not args.check:
        append_log(f"## [{compiled_at}] compile | {len(changed)} page(s) changed — {summary}")

    if args.check:
        print(f"wiki-compile --check: {len(changed)} page(s) would change, {unchanged} up to date")
        for c in changed[:20]:
            print(f"  {c}")
        if len(changed) > 20:
            print(f"  ... and {len(changed) - 20} more")
        return 1 if changed else 0

    print(f"wiki-compile: wrote {written} page(s), {unchanged} unchanged ({summary})")
    warned = [p for p in pages if p.warnings]
    for p in warned:
        for w in p.warnings:
            print(f"  warning: {p.name}: {w}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
