# k8s/overlays/multi-tenant-pattern/tenants/client-b/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../org
  - ./namespace.yaml

labels:
  - pairs:
      tenant: client-b
