# Generic Local Storage PersistentVolume for Node-RED
# This is a template. The overlay is responsible for patching
# the metadata.name and spec.hostPath.path with specific values.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-node-red # A generic, predictable name
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/sebas/smart-home/node-red
    type: DirectoryOrCreate
